################################################################################
## Calibration arguments
################################################################################

calibration-model=None
calibration-correction-type={"ET": "template"}
spline-calibration-envelope-dict=None
spline-calibration-nodes=10
spline-calibration-amplitude-uncertainty-dict=None
spline-calibration-phase-uncertainty-dict=None
calibration-prior-boundary=reflective

################################################################################
## Data generation arguments
################################################################################

ignore-gwpy-data-quality-check=True
gps-tuple=None
gps-file=None
timeslide-file=None
timeslide-dict=None
trigger-time=10
n-simulation=0
data-dict=None
data-format=None
allow-tape=True
channel-dict=None
frame-type-dict=None
data-find-url=None
data-find-urltype=osdf
gaussian-noise=False
zero-noise=True

################################################################################
## Detector arguments
################################################################################

coherence-test=False
################################################################################
## Data generation arguments
################################################################################
detectors=['ET']
duration=8.0
generation-seed=None
psd-dict={"ET": "ET_D_psd.txt", "ET1": "ET_D_psd.txt", "ET2": "ET_D_psd.txt", "ET3": "ET_D_psd.txt"}
psd-fractional-overlap=0.5
post-trigger-duration=2.0
sampling-frequency=4096
psd-length=32
psd-maximum-duration=1024
psd-method=median
psd-start-time=None
maximum-frequency={"ET": 2048, "ET1": 2048, "ET2": 2048, "ET3": 2048, "waveform": 2048}
minimum-frequency={"ET": 20, "ET1": 20, "ET2": 20, "ET3": 20, "waveform": 20}
tukey-roll-off=0.4
resampling-method=lal

################################################################################
## Injection arguments
################################################################################

injection=True
injection-dict={'total_mass': 90, 'mass_ratio': 1, 'a_1': 0.8, 'a_2': 0.8, 'tilt_1': 1.5707963267948966, 'tilt_2': 1.5707963267948966, 'phi_12': 3.141592653589793, 'phi_jl': 0, 'luminosity_distance': 500, 'dec': 0.761, 'ra': 1.94, 'theta_jn': 1.5707963267948966, 'psi': 0.0, 'phase': 0.0, 'geocent_time': 10}
injection-file=None
injection-numbers=None
injection-waveform-approximant=NRSur7dq4
injection-frequency-domain-source-model=None
injection-waveform-arguments=None
injection-waveform-generator-constructor-dict=None

################################################################################
## Job submission arguments
################################################################################

accounting=None
accounting-user=None
################################################################################
## Job submission arguments
################################################################################
label=sanity
local=False
local-generation=True
generation-pool=local-pool
local-plot=False
outdir=/holohome/jannik.mielke/subdom_asym/PE/bilby_asym/run2/sanity/outdir
overwrite-outdir=True
periodic-restart-time=28800
request-disk=5
request-memory=8.0
request-memory-generation=None
request-cpus=80
conda-env=None
################################################################################
## Slurm Settings
################################################################################
scheduler=slurm
scheduler-args=None
scheduler-module=None
scheduler-env=None
scheduler-analysis-time=10-00:00:00
submit=False
condor-job-priority=0
transfer-files=True
additional-transfer-paths=None
environment-variables=None
getenv=None
disable-hdf5-locking=False
log-directory=None
osg=False
desired-sites=None
analysis-executable=None
analysis-executable-parser=None
scitoken-issuer=None
container=None

################################################################################
## Likelihood arguments
################################################################################

calibration-marginalization=False
distance-marginalization=True
distance-marginalization-lookup-table=None
phase-marginalization=False
################################################################################
## Likelihood arguments
################################################################################
time-marginalization=False
jitter-time=True
reference-frame=sky
time-reference=geocent
likelihood-type=GravitationalWaveTransient
calibration-lookup-table=None
number-of-response-curves=1000
roq-folder=None
roq-linear-matrix=None
roq-quadratic-matrix=None
roq-weights=None
roq-weight-format=hdf5
roq-scale-factor=1
fiducial-parameters=None
update-fiducial-parameters=False
epsilon=0.025
extra-likelihood-kwargs=None

################################################################################
## Output arguments
################################################################################

plot-trace=False
###############################################################################
## Output arguments
###############################################################################
plot-data=True
plot-injection=True
plot-spectrogram=False
plot-calibration=False
plot-corner=False
plot-marginal=False
plot-skymap=False
plot-waveform=True
plot-format=png
create-summary=False
email=None
notification=Never
queue=None
existing-dir=None
webdir=None
summarypages-arguments=None
result-format=json
final-result=True
final-result-nsamples=20000

################################################################################
## Prior arguments
################################################################################

################################################################################
## Prior arguments
################################################################################
default-prior=BBHPriorDict
deltaT=0.02
prior-file=None
prior-dict={chirp_mass = bilby.gw.prior.UniformInComponentsChirpMass(name='chirp_mass', minimum=15, maximum=45), mass_ratio = bilby.gw.prior.UniformInComponentsMassRatio(name='mass_ratio', minimum=0.167, maximum=1), mass_1 = Constraint(name='mass_1', minimum=1.001398, maximum=1000), mass_2 = Constraint(name='mass_2', minimum=1.001398, maximum=1000), a_1 = Uniform(name='a_1', minimum=0, maximum=0.99), a_2 = Uniform(name='a_2', minimum=0, maximum=0.99), tilt_1 = Sine(name='tilt_1', minimum=0, maximum=np.pi), tilt_2 = Sine(name='tilt_2', minimum=0, maximum=np.pi), phi_12 = Uniform(name='phi_12', minimum=0, maximum=2*np.pi, boundary='periodic'), phi_jl = Uniform(name='phi_jl', minimum=0, maximum=2*np.pi, boundary='periodic'), luminosity_distance = bilby.gw.prior.UniformSourceFrame(name='luminosity_distance', minimum=100, maximum=4000), dec = Cosine(name='dec'), ra = Uniform(name='ra', minimum=0, maximum=2*np.pi, boundary='periodic'), theta_jn = Sine(name='theta_jn'), psi = Uniform(name='psi', minimum=0, maximum=np.pi, boundary='periodic'), phase = Uniform(name='phase', minimum=0, maximum=2*np.pi, boundary='periodic'), geocent_time = Uniform(minimum=9.9, maximum=10.1, name='geocent_time', boundary=None)}
enforce-signal-duration=True

################################################################################
## Post processing arguments
################################################################################

postprocessing-executable=None
postprocessing-arguments=None
single-postprocessing-executable=None
single-postprocessing-arguments=None

################################################################################
## Sampler arguments
################################################################################

################################################################################
## Sampler settings
###############################################################################
sampler=dynesty
sampling-seed=None
n-parallel=1
sampler-kwargs={'nlive': 2000, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'npool': 80, 'update_interval': 600, 'enlarge': 1.5}
reweighting-configuration=None
reweight-nested-samples=True

################################################################################
## Waveform arguments
################################################################################

################################################################################
## Waveform arguments
################################################################################
waveform-generator=bilby.gw.waveform_generator.WaveformGenerator
waveform-generator-constructor-dict=None
reference-frequency=20.0
waveform-approximant=NRSur7dq4_sanity
catch-waveform-errors=True
pn-spin-order=-1
pn-tidal-order=-1
pn-phase-order=-1
pn-amplitude-order=0
numerical-relativity-file=None
waveform-arguments-dict=None
mode-array=None
frequency-domain-source-model=lal_binary_black_hole
conversion-function=None
generation-function=None

################################################################################
## Global settings
################################################################################

cosmology=Planck15

